version: '2.2'
services:
  logstash:
      container_name: logstash
      image: docker.elastic.co/logstash/logstash:6.3.2
      ports:
        - 5044:5044

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    container_name: elasticsearch
    environment:
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  # elasticsearch2:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
  #   container_name: elasticsearch2
  #   environment:
  #     - cluster.name=es-docker-cluster
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #     - "discovery.zen.ping.unicast.hosts=elasticsearch"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   volumes:
  #     - esdata2:/usr/share/elasticsearch/data
  #   networks:
  #     - esnet

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:6.3.2
    # environment:
    #   ELASTICSEARCH_URL: "http://localhost:9200"
    networks:
      - esnet
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local

networks:
  esnet:
